# Generated by Django 3.2.7 on 2021-09-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Outfordelivery', 'Outfordelivery'), ('Delivered', 'Delivered')], max_length=100, null=True),
        ),
    ]
